# 服务器启动的端口号
server:
  port: 8091
#mybatis 配置
mybatis:
  #config-location: classpath:com/cxk/mapper/VideoMapper.xml
  mapper-locations: classpath:com/cxk/mapper/*.xml
spring:
  mvc:
    ../../static-path-pattern: /**
  resources:
    ../../static-locations: classpath:/../../static/
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.198.5:3306/gamehub?serverTimezone=GMT
    username: gamehub
    password: eeKfWH8NRz
    #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:                                         #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka   #单机
    register-with-eureka: true
    fetch-registry: true

#pagehelper分页插件配置
pagehelper:
  #<!-- 启用合理化时，如果pageNum<1或pageNum>pages会返回首页或尾页 -->
  reasonable: true
  #<!-- pageSize=0相当于没有执行分页查询，但是返回结果仍然是Page类型 -->
  pageSizeZero: true