# 服务器启动的端口号
server:
  port: 8090
#mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  reasonable: true
  page-size-zero: true
  pageSizeZero: true
# 服务器名称
spring:
  application:
    name: download-client                         #微服务名
  datasource:
    url: jdbc:mysql://47.102.198.5:3306/gamehub?serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    username: gamehub
    password: eeKfWH8NRz
#eureka 配置
eureka:
  client:                                         #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka   #单机
    register-with-eureka: true
    fetch-registry: true


#  instance:
#    instance-id: microservice-dept8001
#    prefer-ip-address: true                       #访问路径可以显示IP地址
#    leaseRenewalIntervalInSeconds: 10             #租期更新时间间隔（默认30秒）
#    leaseExpirationDurationInSeconds: 30          #租期到期时间（默认90秒）

